### PR TITLE
Keep AreaThresholdSensor working on HA 2026.8

### LINKED ISSUE #623: [Bug]: Illuminance threshold light sensor missing on HA 2026.8 (beta) — ThresholdSensor.__init__() no longer accepts `hass`
After upgrading Home Assistant Core to the 2026.8 beta, the calculated "Area Light Sensor" (illuminance threshold) entity is silently missing for my areas, e.g.:

binary_sensor.magic_areas_threshold_exterior_threshold_light

No repair/notification is shown in the UI — the entity is just gone.

Root cause

custom_components/magic_areas/threshold.py calls:

ThresholdSensor.__init__(
    self,
    hass=hass,
    entity_id=entity_id,
    name=EMPTY_STRING,
    unique_id=self.unique_id,
    lower=lower,
    upper=upper,
    hysteresis=hysteresis,
    device_class=device_class,
)

As of HA core 2026.8, ThresholdSensor.__init__() (in homeassistant/components/threshold/binary_sensor.py) no longer accepts a hass keyword argument at all:

def __init__(
    self,
    *,
    entity_id: str,
    name: str,
    lower: float | None,
    upper: float | None,
    hysteresis: float,
    device_class: BinarySensorDeviceClass | None,
    unique_id: str | None,
    device: DeviceEntry | None = None,
) -> None:

self.hass is now populated automatically by the entity platform via async_added_to_hass() instead of being passed into __init__.

Passing hass=hass therefore raises:

TypeError: ThresholdSensor.__init__() got an unexpected keyword argument 'hass'

This exception is caught by the broad except Exception in create_illuminance_threshold(), logged as:

%s: Error creating calculated light sensor: %s

and the function returns None — so the entity is dropped without any visible error/repair in the frontend, only a debug/error log line.

Suggested fix

Drop the hass=hass kwarg from the ThresholdSensor.__init__() call in AreaThresholdSensor.__init__ (the outer hass parameter can stay, in case MagicEntity.__init__ still needs it):

         MagicEntity.__init__(
             self, area, domain=BINARY_SENSOR_DOMAIN, translation_key=device_class
         )
         ThresholdSensor.__init__(
             self,
-            hass=hass,
             entity_id=entity_id,
             name=EMPTY_STRING,
             unique_id=self.unique_id,
             lower=lower,
             upper=upper,
             hysteresis=hysteresis,
             device_class=device_class,
         )

I've tested this change locally (overriding custom_components/magic_areas/threshold.py) and it resolves the issue — the entity is created again on 2026.8 beta.

To Reproduce

1. Run HA Core 2026.8 (beta)
2. Have Magic Areas with illuminance aggregation + threshold enabled for an area/meta-area
3. Reload/restart HA
4. binary_sensor...threshold_light entity for that area is missing; log shows "Error creating calculated light sensor: ...unexpected keyword argument 'hass'"

Environment

- Home Assistant Core: 2026.8.0 (beta)
- Magic Areas version: 4.4.1
- Installation type: HAOS / paedML-managed NUC10 setup

Additional context

This is the same class of breaking change that hit Threshold sensor initialization in HA 2024.7 and 2025.8, each requiring a small hotfix release (see #401/#541 in this repo). This one just moves hass out of __init__ entirely instead of changing initial-state handling.

### PR DESCRIPTION
**Pull request by proscar87**
## Problem

HA 2026.8 removed the `hass` parameter from `ThresholdSensor.__init__` (`homeassistant.components.threshold.binary_sensor`), so creating the illuminance threshold sensor fails on 2026.8 betas and the sensor goes missing (#623).

## Fix

Build the `ThresholdSensor.__init__` kwargs and pass `hass` only when the installed signature still accepts it — addressing the compat concern raised in the issue: the same code works on both pre-2026.8 (which requires `hass`) and 2026.8+ (which rejects it), with no version pinning.

## Testing

- `pytest tests/test_threshold.py` passes against **homeassistant 2026.8.0b4** (the version that removed the parameter), pulled in by current `pytest-homeassistant-custom-component` — i.e. the new code path is exercised.
- The signature-detection logic verified against both `__init__` shapes (with and without `hass`).

Fixes #623

### CODE REVIEW

**Comment by jseidl** [comment]
Thanks, will merge this soon.
